# Generated by Django 4.2.23 on 2025-09-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
        migrations.AlterModelOptions(
            name="linkcategory",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Link category",
                "verbose_name_plural": "Link categories",
            },
        ),
        migrations.AlterField(
            model_name="link",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="contacts.linkcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="show"),
        ),
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(max_length=50, verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="link",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="linkcategory",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Category name"
            ),
        ),
        migrations.AlterField(
            model_name="linkcategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="linkcategory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
