# Generated by Django 4.2.23 on 2025-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_link_options_alter_linkcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
    ]
