# Generated by Django 4.2.23 on 2025-08-31 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_alter_photo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Дата съёмки"
            ),
        ),
    ]
