# Generated by Django 4.1.11 on 2024-05-02 18:42

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="public offer", max_length=100)),
                ("text", django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
