# Generated by Django 4.2.23 on 2025-08-31 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "verbose_name": "Terms & Conditions",
                "verbose_name_plural": "Terms & Conditions",
            },
        ),
    ]
