# Generated by Django 4.2.23 on 2025-08-31 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "verbose_name": "Delivery method",
                "verbose_name_plural": "Delivery methods",
            },
        ),
    ]
